global using Microsoft.JSInterop;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Routing;
global using Microsoft.FluentUI.AspNetCore.Components;
global using System.Globalization;
global using System.ComponentModel;
global using WebVella.Tefter.Demo.Components;
global using WebVella.Tefter.Demo.Models;
global using WebVella.Tefter.Demo.Data;